<?php

namespace Modules\Accommodation\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Accommodation\Entities\Country;

class CountrySeederTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::insert($this->getCountryData());
    }

    private function getCountryData()
    {
        $countries = array(
            array('name_hr' => 'Afganistan','name_en' => 'Afghanistan','name_ru' => 'Афганистан','local_name' => 'افغانستان','global_name' => 'Afghanistan','code' => 'AF','dial_code' => '93'),
            array('name_hr' => 'Albanija','name_en' => 'Albania','name_ru' => 'Албания','local_name' => 'Shqipëria','global_name' => 'Albania','code' => 'AL','dial_code' => '355'),
            array('name_hr' => 'Alžir','name_en' => 'Algeria','name_ru' => 'Алжир','local_name' => 'الجزائر','global_name' => 'Algeria','code' => 'DZ','dial_code' => '213'),
            array('name_hr' => 'Američka Samoa','name_en' => 'American Samoa','name_ru' => 'Американское Самоа','local_name' => 'American Samoa','global_name' => 'American Samoa','code' => 'AS','dial_code' => '1684'),
            array('name_hr' => 'Američki Djevičanski Otoci','name_en' => 'US Virgin Islands','name_ru' => 'Виргинские о-ва (США)','local_name' => 'US Virgin Islands','global_name' => 'US Virgin Islands','code' => 'VI','dial_code' => '1340'),
            array('name_hr' => 'Andora','name_en' => 'Andorra','name_ru' => 'Андорра','local_name' => 'Andorra','global_name' => 'Andorra','code' => 'AD','dial_code' => '376'),
            array('name_hr' => 'Angola','name_en' => 'Angola','name_ru' => 'Ангола','local_name' => 'Anguila','global_name' => 'Angola','code' => 'AO','dial_code' => '244'),
            array('name_hr' => 'Anguila','name_en' => 'Anguilla','name_ru' => 'Ангилья','local_name' => 'Anguilla','global_name' => 'Anguilla','code' => 'AI','dial_code' => '1264'),
            array('name_hr' => 'Antarktik','name_en' => 'Antarctica','name_ru' => 'Антарктида','local_name' => 'Antarctica','global_name' => 'Antarctica','code' => 'AQ','dial_code' => ''),
            array('name_hr' => 'Antigua i Barbuda','name_en' => 'Antigua and Barbuda','name_ru' => 'Антигуа и Барбуда','local_name' => 'Antigua and Barbuda','global_name' => 'Antigua and Barbuda','code' => 'AG','dial_code' => '1268'),
            array('name_hr' => 'Argentina','name_en' => 'Argentina','name_ru' => 'Аргентина','local_name' => 'Argentina','global_name' => 'Argentina','code' => 'AR','dial_code' => '54'),
            array('name_hr' => 'Armenija','name_en' => 'Armenia','name_ru' => 'Армения','local_name' => 'Հայաստան','global_name' => 'Armenia','code' => 'AM','dial_code' => '374'),
            array('name_hr' => 'Aruba','name_en' => 'Aruba','name_ru' => 'Аруба','local_name' => 'Aruba','global_name' => 'Aruba','code' => 'AW','dial_code' => '297'),
            array('name_hr' => 'Australija','name_en' => 'Australia','name_ru' => 'Австралия','local_name' => 'Australia','global_name' => 'Australia','code' => 'AU','dial_code' => '61'),
            array('name_hr' => 'Austrija','name_en' => 'Austria','name_ru' => 'Австрия','local_name' => 'Österreich','global_name' => 'Austria','code' => 'AT','dial_code' => '43'),
            array('name_hr' => 'Azerbajdžan','name_en' => 'Azerbaijan','name_ru' => 'Азербайджан','local_name' => 'Azərbaycan','global_name' => 'Azerbaijan','code' => 'AZ','dial_code' => '994'),
            array('name_hr' => 'Bahami','name_en' => 'Bahamas','name_ru' => 'Багамские о-ва','local_name' => 'Bahamas','global_name' => 'Bahamas','code' => 'BS','dial_code' => '1242'),
            array('name_hr' => 'Bahrein','name_en' => 'Bahrain','name_ru' => 'Бахрейн','local_name' => '‫البحرين','global_name' => 'Bahrain','code' => 'BH','dial_code' => '973'),
            array('name_hr' => 'Bangladeš','name_en' => 'Bangladesh','name_ru' => 'Бангладеш','local_name' => 'বাংলাদেশ','global_name' => 'Bangladesh','code' => 'BD','dial_code' => '880'),
            array('name_hr' => 'Barbados','name_en' => 'Barbados','name_ru' => 'Барбадос','local_name' => 'Barbados','global_name' => 'Barbados','code' => 'BB','dial_code' => '1246'),
            array('name_hr' => 'Belgija','name_en' => 'Belgium','name_ru' => 'Бельгия','local_name' => 'België','global_name' => 'Belgium','code' => 'BE','dial_code' => '32'),
            array('name_hr' => 'Belize','name_en' => 'Belize','name_ru' => 'Белиз','local_name' => 'Belize','global_name' => 'Belize','code' => 'BZ','dial_code' => '501'),
            array('name_hr' => 'Benin','name_en' => 'Benin','name_ru' => 'Бенин','local_name' => 'Bénin','global_name' => 'Benin','code' => 'BJ','dial_code' => '229'),
            array('name_hr' => 'Bermuda','name_en' => 'Bermuda','name_ru' => 'Бермудские о-ва','local_name' => 'Bermuda','global_name' => 'Bermuda','code' => 'BM','dial_code' => '1441'),
            array('name_hr' => 'Bjelokosna Obala','name_en' => 'Cote d\'Ivoire','name_ru' => 'Кот д’Ивуар','local_name' => 'Côte d’Ivoire','global_name' => 'Cote d\'Ivoire','code' => 'CI','dial_code' => '225'),
            array('name_hr' => 'Bjelorusija','name_en' => 'Belarus','name_ru' => 'Беларусь','local_name' => 'Беларусь','global_name' => 'Belarus','code' => 'BY','dial_code' => '375'),
            array('name_hr' => 'Bocvana','name_en' => 'Botswana','name_ru' => 'Ботсвана','local_name' => 'Botswana','global_name' => 'Botswana','code' => 'BW','dial_code' => '267'),
            array('name_hr' => 'Bosna i Hercegovina','name_en' => 'Bosnia and Herzegovina','name_ru' => 'Босния и Герцеговина','local_name' => 'Босна и Херцеговина','global_name' => 'Bosnia and Herzegovina','code' => 'BA','dial_code' => '387'),
            array('name_hr' => 'Božićni Otok','name_en' => 'Christmas Island','name_ru' => 'О-в Рождества','local_name' => 'Christmas Island','global_name' => 'Christmas Island','code' => 'CX','dial_code' => ''),
            array('name_hr' => 'Brazil','name_en' => 'Brazil','name_ru' => 'Бразилия','local_name' => 'Brasil','global_name' => 'Brazil','code' => 'BR','dial_code' => '55'),
            array('name_hr' => 'Britanski Djevičanski Otoci','name_en' => 'British Virgin Islands','name_ru' => 'Британские Виргинские о-ва','local_name' => 'British Virgin Islands','global_name' => 'British Virgin Islands','code' => 'VG','dial_code' => '1284'),
            array('name_hr' => 'Britanski Teritorij Indijskog Oceana','name_en' => 'British Indian Ocean Territory','name_ru' => 'Британская территория в Индийском океане','local_name' => 'British Indian Ocean Territory','global_name' => 'British Indian Ocean Territory','code' => 'IO','dial_code' => ''),
            array('name_hr' => 'Brunej','name_en' => 'Brunei','name_ru' => 'Бруней-Даруссалам','local_name' => 'Brunei','global_name' => 'Brunei','code' => 'BN','dial_code' => '673'),
            array('name_hr' => 'Bugarska','name_en' => 'Bulgaria','name_ru' => 'Болгария','local_name' => 'България','global_name' => 'Bulgaria','code' => 'BG','dial_code' => '359'),
            array('name_hr' => 'Burkina Faso','name_en' => 'Burkina Faso','name_ru' => 'Буркина Фасо','local_name' => 'Burkina Faso','global_name' => 'Burkina Faso','code' => 'BF','dial_code' => '226'),
            array('name_hr' => 'Burundi','name_en' => 'Burundi','name_ru' => 'Бурунди','local_name' => 'Uburundi','global_name' => 'Burundi','code' => 'BI','dial_code' => '257'),
            array('name_hr' => 'Butan','name_en' => 'Bhutan','name_ru' => 'Бутан','local_name' => 'འབྲུག','global_name' => 'Bhutan','code' => 'BT','dial_code' => '975'),
            array('name_hr' => 'Ceuta i Melilla','name_en' => 'Ceuta and Melilla','name_ru' => 'Сеута и Мелилья','local_name' => 'Ceuta y Melilla','global_name' => 'Ceuta and Melilla','code' => 'EA','dial_code' => ''),
            array('name_hr' => 'Cipar','name_en' => 'Cyprus','name_ru' => 'Кипр','local_name' => 'Κύπρος','global_name' => 'Cyprus','code' => 'CY','dial_code' => '357'),
            array('name_hr' => 'Crna Gora','name_en' => 'Montenegro','name_ru' => 'Черногория','local_name' => 'Crna Gora','global_name' => 'Montenegro','code' => 'ME','dial_code' => '382'),
            array('name_hr' => 'Curaçao','name_en' => 'Curaçao','name_ru' => 'Кюрасао','local_name' => 'Curaçao','global_name' => 'Curaçao','code' => 'CW','dial_code' => '599'),
            array('name_hr' => 'Čad','name_en' => 'Chad','name_ru' => 'Чад','local_name' => 'Tchad','global_name' => 'Chad','code' => 'TD','dial_code' => '235'),
            array('name_hr' => 'Češka Republika','name_en' => 'Czech Republic','name_ru' => 'Чехия','local_name' => 'Česká republika','global_name' => 'Czech Republic','code' => 'CZ','dial_code' => '420'),
            array('name_hr' => 'Čile','name_en' => 'Chile','name_ru' => 'Чили','local_name' => 'Chile','global_name' => 'Chile','code' => 'CL','dial_code' => '56'),
            array('name_hr' => 'Danska','name_en' => 'Denmark','name_ru' => 'Дания','local_name' => 'Danmark','global_name' => 'Denmark','code' => 'DK','dial_code' => '45'),
            array('name_hr' => 'Demokratska Republika Kongo','name_en' => 'Congo Dem Rep','name_ru' => 'Демократическая Республика Конго','local_name' => 'Jamhuri ya Kidemokrasia ya Kongo','global_name' => 'Congo Dem Rep','code' => 'CD','dial_code' => '243'),
            array('name_hr' => 'Diego Garcia','name_en' => 'Diego Garcia','name_ru' => 'Диего-Гарсия','local_name' => 'Diego Garcia','global_name' => 'Diego Garcia','code' => 'DG','dial_code' => '246'),
            array('name_hr' => 'Dominika','name_en' => 'Dominica','name_ru' => 'Доминика','local_name' => 'Dominica','global_name' => 'Dominica','code' => 'DM','dial_code' => '1767'),
            array('name_hr' => 'Dominikanska Republika','name_en' => 'Dominican Republic','name_ru' => 'Доминиканская Республика','local_name' => 'República Dominicana','global_name' => 'Dominican Republic','code' => 'DO','dial_code' => '1809'),
            array('name_hr' => 'Džibuti','name_en' => 'Djibouti','name_ru' => 'Джибути','local_name' => 'Djibouti','global_name' => 'Djibouti','code' => 'DJ','dial_code' => '253'),
            array('name_hr' => 'Egipat','name_en' => 'Egypt','name_ru' => 'Египет','local_name' => '‫مصر‬‎','global_name' => 'Egypt','code' => 'EG','dial_code' => '20'),
            array('name_hr' => 'Ekvador','name_en' => 'Ecuador','name_ru' => 'Эквадор','local_name' => 'Ecuador','global_name' => 'Ecuador','code' => 'EC','dial_code' => '593'),
            array('name_hr' => 'Ekvatorska Gvineja','name_en' => 'Equatorial Guinea','name_ru' => 'Экваториальная Гвинея','local_name' => 'Guinea Ecuatorial','global_name' => 'Equatorial Guinea','code' => 'GQ','dial_code' => '240'),
            array('name_hr' => 'El Salvador','name_en' => 'El Salvador','name_ru' => 'Сальвадор','local_name' => 'El Salvador','global_name' => 'El Salvador','code' => 'SV','dial_code' => '503'),
            array('name_hr' => 'Eritreja','name_en' => 'Eritrea','name_ru' => 'Эритрея','local_name' => 'Eritrea','global_name' => 'Eritrea','code' => 'ER','dial_code' => '291'),
            array('name_hr' => 'Estonija','name_en' => 'Estonia','name_ru' => 'Эстония','local_name' => 'Eesti','global_name' => 'Estonia','code' => 'EE','dial_code' => '372'),
            array('name_hr' => 'Etiopija','name_en' => 'Ethiopia','name_ru' => 'Эфиопия','local_name' => 'Ethiopia','global_name' => 'Ethiopia','code' => 'ET','dial_code' => '251'),
            array('name_hr' => 'Falklandski Otoci','name_en' => 'Falkland Islands','name_ru' => 'Фолклендские о-ва','local_name' => 'Falkland Islands (Islas Malvinas)','global_name' => 'Falkland Islands','code' => 'FK','dial_code' => '500'),
            array('name_hr' => 'Farski Otoci','name_en' => 'Faroe Islands','name_ru' => 'Фарерские о-ва','local_name' => 'Føroyar','global_name' => 'Faroe Islands','code' => 'FO','dial_code' => '298'),
            array('name_hr' => 'Fidži','name_en' => 'Fiji','name_ru' => 'Фиджи','local_name' => 'Fiji','global_name' => 'Fiji','code' => 'FJ','dial_code' => '679'),
            array('name_hr' => 'Filipini','name_en' => 'Philippines','name_ru' => 'Филиппины','local_name' => 'Philippines','global_name' => 'Philippines','code' => 'PH','dial_code' => '63'),
            array('name_hr' => 'Finska','name_en' => 'Finland','name_ru' => 'Финляндия','local_name' => 'Suomi','global_name' => 'Finland','code' => 'FI','dial_code' => '358'),
            array('name_hr' => 'Francuska','name_en' => 'France','name_ru' => 'Франция','local_name' => 'France','global_name' => 'France','code' => 'FR','dial_code' => '33'),
            array('name_hr' => 'Francuska Gvajana','name_en' => 'French Guiana','name_ru' => 'Французская Гвиана','local_name' => 'Guyane française','global_name' => 'French Guiana','code' => 'GF','dial_code' => '594'),
            array('name_hr' => 'Francuska Polinezija','name_en' => 'French Polynesia','name_ru' => 'Французская Полинезия','local_name' => 'Polynésie française','global_name' => 'French Polynesia','code' => 'PF','dial_code' => '689'),
            array('name_hr' => 'Francuski Južni Teritoriji','name_en' => 'French Southern and Antarctic Lands','name_ru' => 'Французские Южные Территории','local_name' => 'Terres australes françaises','global_name' => 'French Southern and Antarctic Lands','code' => 'TF','dial_code' => ''),
            array('name_hr' => 'Gabon','name_en' => 'Gabon','name_ru' => 'Габон','local_name' => 'Gabon','global_name' => 'Gabon','code' => 'GA','dial_code' => '241'),
            array('name_hr' => 'Gambija','name_en' => 'Gambia','name_ru' => 'Гамбия','local_name' => 'Gambia','global_name' => 'Gambia','code' => 'GM','dial_code' => '220'),
            array('name_hr' => 'Gana','name_en' => 'Ghana','name_ru' => 'Гана','local_name' => 'Gaana','global_name' => 'Ghana','code' => 'GH','dial_code' => '233'),
            array('name_hr' => 'Gibraltar','name_en' => 'Gibraltar','name_ru' => 'Гибралтар','local_name' => 'Gibraltar','global_name' => 'Gibraltar','code' => 'GI','dial_code' => '350'),
            array('name_hr' => 'Grad Vatikan','name_en' => 'Vatican City','name_ru' => 'Ватикан','local_name' => 'Città del Vaticano','global_name' => 'Vatican City','code' => 'VA','dial_code' => '379'),
            array('name_hr' => 'Grčka','name_en' => 'Greece','name_ru' => 'Греция','local_name' => 'Ελλάδα','global_name' => 'Greece','code' => 'GR','dial_code' => '30'),
            array('name_hr' => 'Grenada','name_en' => 'Grenada','name_ru' => 'Гренада','local_name' => 'Grenada','global_name' => 'Grenada','code' => 'GD','dial_code' => '1473'),
            array('name_hr' => 'Grenland','name_en' => 'Greenland','name_ru' => 'Гренландия','local_name' => 'Kalaallit Nunaat','global_name' => 'Greenland','code' => 'GL','dial_code' => '299'),
            array('name_hr' => 'Gruzija','name_en' => 'Georgia','name_ru' => 'Грузия','local_name' => 'საქართველო','global_name' => 'Georgia','code' => 'GE','dial_code' => '995'),
            array('name_hr' => 'Guadeloupe','name_en' => 'Guadeloupe','name_ru' => 'Гваделупа','local_name' => 'Guadeloupe','global_name' => 'Guadeloupe','code' => 'GP','dial_code' => '590'),
            array('name_hr' => 'Guam','name_en' => 'Guam','name_ru' => 'Гуам','local_name' => 'Guam','global_name' => 'Guam','code' => 'GU','dial_code' => '1671'),
            array('name_hr' => 'Guernsey','name_en' => 'Guernsey','name_ru' => 'Гернси','local_name' => 'Guernsey','global_name' => 'Guernsey','code' => 'GG','dial_code' => ''),
            array('name_hr' => 'Gvajana','name_en' => 'Guyana','name_ru' => 'Гайана','local_name' => 'Guyana','global_name' => 'Guyana','code' => 'GY','dial_code' => '592'),
            array('name_hr' => 'Gvatemala','name_en' => 'Guatemala','name_ru' => 'Гватемала','local_name' => 'Guatemala','global_name' => 'Guatemala','code' => 'GT','dial_code' => '502'),
            array('name_hr' => 'Gvineja','name_en' => 'Guinea','name_ru' => 'Гвинея','local_name' => 'Guinée','global_name' => 'Guinea','code' => 'GN','dial_code' => '224'),
            array('name_hr' => 'Gvineja Bisau','name_en' => 'Guinea Bissau','name_ru' => 'Гвинея-Бисау','local_name' => 'Guiné Bissau','global_name' => 'Guinea Bissau','code' => 'GW','dial_code' => '245'),
            array('name_hr' => 'Haiti','name_en' => 'Haiti','name_ru' => 'Гаити','local_name' => 'Haiti','global_name' => 'Haiti','code' => 'HT','dial_code' => '509'),
            array('name_hr' => 'Honduras','name_en' => 'Honduras','name_ru' => 'Гондурас','local_name' => 'Honduras','global_name' => 'Honduras','code' => 'HN','dial_code' => '504'),
            array('name_hr' => 'Hong Kong','name_en' => 'Hong Kong','name_ru' => 'Гонконг','local_name' => '香港','global_name' => 'Hong Kong','code' => 'HK','dial_code' => '852'),
            array('name_hr' => 'Hrvatska','name_en' => 'Croatia','name_ru' => 'Хорватия','local_name' => 'Hrvatska','global_name' => 'Croatia','code' => 'HR','dial_code' => '385'),
            array('name_hr' => 'Indija','name_en' => 'India','name_ru' => 'Индия','local_name' => 'भारत','global_name' => 'India','code' => 'IN','dial_code' => '91'),
            array('name_hr' => 'Indonezija','name_en' => 'Indonesia','name_ru' => 'Индонезия','local_name' => 'Indonesia','global_name' => 'Indonesia','code' => 'ID','dial_code' => '62'),
            array('name_hr' => 'Irak','name_en' => 'Iraq','name_ru' => 'Ирак','local_name' => 'العراق‬‎','global_name' => 'Iraq','code' => 'IQ','dial_code' => '964'),
            array('name_hr' => 'Iran','name_en' => 'Iran','name_ru' => 'Иран','local_name' => '‫ایران','global_name' => 'Iran','code' => 'IR','dial_code' => '98'),
            array('name_hr' => 'Irska','name_en' => 'Ireland','name_ru' => 'Ирландия','local_name' => 'Ireland','global_name' => 'Ireland','code' => 'IE','dial_code' => '353'),
            array('name_hr' => 'Island','name_en' => 'Iceland','name_ru' => 'Исландия','local_name' => 'Ísland','global_name' => 'Iceland','code' => 'IS','dial_code' => '354'),
            array('name_hr' => 'Istočni Timor','name_en' => 'Timor-Leste','name_ru' => 'Тимор-Лешти','local_name' => 'Timor-Leste','global_name' => 'Timor-Leste','code' => 'TL','dial_code' => '670'),
            array('name_hr' => 'Italija','name_en' => 'Italy','name_ru' => 'Италия','local_name' => 'Italia','global_name' => 'Italy','code' => 'IT','dial_code' => '39'),
            array('name_hr' => 'Izrael','name_en' => 'Israel','name_ru' => 'Израиль','local_name' => 'ישראל‬‎','global_name' => 'Israel','code' => 'IL','dial_code' => '972'),
            array('name_hr' => 'Jamajka','name_en' => 'Jamaica','name_ru' => 'Ямайка','local_name' => 'Jamaica','global_name' => 'Jamaica','code' => 'JM','dial_code' => '1876'),
            array('name_hr' => 'Japan','name_en' => 'Japan','name_ru' => 'Япония','local_name' => '日本','global_name' => 'Japan','code' => 'JP','dial_code' => '81'),
            array('name_hr' => 'Jemen','name_en' => 'Yemen','name_ru' => 'Йемен','local_name' => '‫اليمن‬‎','global_name' => 'Yemen','code' => 'YE','dial_code' => '967'),
            array('name_hr' => 'Jersey','name_en' => 'Bailiwick of Jersey','name_ru' => 'Джерси','local_name' => 'Jersey','global_name' => 'Bailiwick of Jersey','code' => 'JE','dial_code' => ''),
            array('name_hr' => 'Jordan','name_en' => 'Jordan','name_ru' => 'Иордания','local_name' => 'الأردن','global_name' => 'Jordan','code' => 'JO','dial_code' => '962'),
            array('name_hr' => 'Južna Gruzija i Južni Sendvič Otoci','name_en' => 'South Georgia and the South Sandwich Islands','name_ru' => 'Южн. Джорджия и Южн. Сандвичевы о-ва','local_name' => 'South Georgia and the South Sandwich Islands','global_name' => 'South Georgia and the South Sandwich Islands','code' => 'GS','dial_code' => ''),
            array('name_hr' => 'Južna Koreja','name_en' => 'South Korea','name_ru' => 'Республика Корея','local_name' => '대한민국','global_name' => 'South Korea','code' => 'KR','dial_code' => '82'),
            array('name_hr' => 'Južni Sudan','name_en' => 'South Sudan','name_ru' => 'Южный Судан','local_name' => 'جنوب السودان','global_name' => 'South Sudan','code' => 'SS','dial_code' => '211'),
            array('name_hr' => 'Južnoafrička Republika','name_en' => 'South Africa','name_ru' => 'ЮАР','local_name' => 'South Africa','global_name' => 'South Africa','code' => 'ZA','dial_code' => '27'),
            array('name_hr' => 'Kajmanski Otoci','name_en' => 'Cayman Islands','name_ru' => 'Каймановы о-ва','local_name' => 'Cayman Islands','global_name' => 'Cayman Islands','code' => 'KY','dial_code' => '1345'),
            array('name_hr' => 'Kambodža','name_en' => 'Cambodia','name_ru' => 'Камбоджа','local_name' => 'កម្ពុជា','global_name' => 'Cambodia','code' => 'KH','dial_code' => '855'),
            array('name_hr' => 'Kamerun','name_en' => 'Cameroon','name_ru' => 'Камерун','local_name' => 'Cameroun','global_name' => 'Cameroon','code' => 'CM','dial_code' => '237'),
            array('name_hr' => 'Kanada','name_en' => 'Canada','name_ru' => 'Канада','local_name' => 'Canada','global_name' => 'Canada','code' => 'CA','dial_code' => '1'),
            array('name_hr' => 'Kanarski Otoci','name_en' => 'Canary Islands','name_ru' => 'Канарские о-ва','local_name' => 'Islas Canarias','global_name' => 'Canary Islands','code' => 'IC','dial_code' => ''),
            array('name_hr' => 'Karipski otoci Nizozemske','name_en' => 'Bonaire, Sint Eustatius, and Saba','name_ru' => 'Бонэйр, Синт-Эстатиус и Саба','local_name' => 'Caribbean Netherlands','global_name' => 'Bonaire, Sint Eustatius, and Saba','code' => 'BQ','dial_code' => '599'),
            array('name_hr' => 'Katar','name_en' => 'Qatar','name_ru' => 'Катар','local_name' => 'قطر‬‎','global_name' => 'Qatar','code' => 'QA','dial_code' => '974'),
            array('name_hr' => 'Kazahstan','name_en' => 'Kazakhstan','name_ru' => 'Казахстан','local_name' => 'Казахстан','global_name' => 'Kazakhstan','code' => 'KZ','dial_code' => '7'),
            array('name_hr' => 'Kenija','name_en' => 'Kenya','name_ru' => 'Кения','local_name' => 'Kenya','global_name' => 'Kenya','code' => 'KE','dial_code' => '254'),
            array('name_hr' => 'Kina','name_en' => 'China','name_ru' => 'Китай','local_name' => '中国','global_name' => 'China','code' => 'CN','dial_code' => '86'),
            array('name_hr' => 'Kirgistan','name_en' => 'Kyrgyzstan','name_ru' => 'Киргизия','local_name' => 'Kyrgyzstan','global_name' => 'Kyrgyzstan','code' => 'KG','dial_code' => '996'),
            array('name_hr' => 'Kiribati','name_en' => 'Kiribati','name_ru' => 'Кирибати','local_name' => 'Kiribati','global_name' => 'Kiribati','code' => 'KI','dial_code' => '686'),
            array('name_hr' => 'Kokosovi (Keeling) otoci','name_en' => 'Cocos (Keeling) Islands','name_ru' => 'Кокосовые о-ва','local_name' => 'Cocos (Keeling) Islands','global_name' => 'Cocos (Keeling) Islands','code' => 'CC','dial_code' => ''),
            array('name_hr' => 'Kolumbija','name_en' => 'Colombia','name_ru' => 'Колумбия','local_name' => 'Colombia','global_name' => 'Colombia','code' => 'CO','dial_code' => '57'),
            array('name_hr' => 'Komori','name_en' => 'Comoros and Mayotte','name_ru' => 'Коморские о-ва','local_name' => 'جزر القمر‬‎','global_name' => 'Comoros and Mayotte','code' => 'KM','dial_code' => '269'),
            array('name_hr' => 'Kongo - Brazzaville','name_en' => 'Congo','name_ru' => 'Конго - Браззавиль','local_name' => 'Congo-Brazzaville','global_name' => 'Congo','code' => 'CG','dial_code' => '242'),
            array('name_hr' => 'Kosovo','name_en' => 'Kosovo','name_ru' => 'Косово','local_name' => 'Косово','global_name' => 'Kosovo','code' => 'XK','dial_code' => ''),
            array('name_hr' => 'Kostarika','name_en' => 'Costa Rica','name_ru' => 'Коста-Рика','local_name' => 'Costa Rica','global_name' => 'Costa Rica','code' => 'CR','dial_code' => '506'),
            array('name_hr' => 'Kuba','name_en' => 'Cuba','name_ru' => 'Куба','local_name' => 'Cuba','global_name' => 'Cuba','code' => 'CU','dial_code' => '53'),
            array('name_hr' => 'Kukovi Otoci','name_en' => 'Cook Islands','name_ru' => 'О-ва Кука','local_name' => 'Cook Islands','global_name' => 'Cook Islands','code' => 'CK','dial_code' => '682'),
            array('name_hr' => 'Kuvajt','name_en' => 'Kuwait','name_ru' => 'Кувейт','local_name' => 'الكويت','global_name' => 'Kuwait','code' => 'KW','dial_code' => '965'),
            array('name_hr' => 'Laos','name_en' => 'Laos','name_ru' => 'Лаос','local_name' => 'ສ.ປ.ປ ລາວ','global_name' => 'Laos','code' => 'LA','dial_code' => '856'),
            array('name_hr' => 'Latvija','name_en' => 'Latvia','name_ru' => 'Латвия','local_name' => 'Latvija','global_name' => 'Latvia','code' => 'LV','dial_code' => '371'),
            array('name_hr' => 'Lesoto','name_en' => 'Lesotho','name_ru' => 'Лесото','local_name' => 'Lesotho','global_name' => 'Lesotho','code' => 'LS','dial_code' => '266'),
            array('name_hr' => 'Libanon','name_en' => 'Lebanon','name_ru' => 'Ливан','local_name' => '‫لبنان‬‎','global_name' => 'Lebanon','code' => 'LB','dial_code' => '961'),
            array('name_hr' => 'Liberija','name_en' => 'Liberia','name_ru' => 'Либерия','local_name' => 'Liberia','global_name' => 'Liberia','code' => 'LR','dial_code' => '231'),
            array('name_hr' => 'Libija','name_en' => 'Libya','name_ru' => 'Ливия','local_name' => '‫ليبيا‬‎','global_name' => 'Libya','code' => 'LY','dial_code' => '218'),
            array('name_hr' => 'Lihtenštajn','name_en' => 'Liechtenstein','name_ru' => 'Лихтенштейн','local_name' => 'Liechtenstein','global_name' => 'Liechtenstein','code' => 'LI','dial_code' => '423'),
            array('name_hr' => 'Litva','name_en' => 'Lithuania','name_ru' => 'Литва','local_name' => 'Lietuva','global_name' => 'Lithuania','code' => 'LT','dial_code' => '370'),
            array('name_hr' => 'Luksemburg','name_en' => 'Luxembourg','name_ru' => 'Люксембург','local_name' => 'Luxembourg','global_name' => 'Luxembourg','code' => 'LU','dial_code' => '352'),
            array('name_hr' => 'Madagaskar','name_en' => 'Madagascar','name_ru' => 'Мадагаскар','local_name' => 'Madagasikara','global_name' => 'Madagascar','code' => 'MG','dial_code' => '261'),
            array('name_hr' => 'Mađarska','name_en' => 'Hungary','name_ru' => 'Венгрия','local_name' => 'Magyarország','global_name' => 'Hungary','code' => 'HU','dial_code' => '36'),
            array('name_hr' => 'Majote','name_en' => 'Mayotte','name_ru' => 'Майотта','local_name' => 'Mayotte','global_name' => 'Mayotte','code' => 'YT','dial_code' => ''),
            array('name_hr' => 'Makao','name_en' => 'Macao','name_ru' => 'Макао','local_name' => '澳門','global_name' => 'Macao','code' => 'MO','dial_code' => '853'),
            array('name_hr' => 'Makedonija','name_en' => 'Macedonia','name_ru' => 'Македония','local_name' => 'Македонија','global_name' => 'Macedonia','code' => 'MK','dial_code' => '389'),
            array('name_hr' => 'Malavi','name_en' => 'Malawi','name_ru' => 'Малави','local_name' => 'Malawi','global_name' => 'Malawi','code' => 'MW','dial_code' => '265'),
            array('name_hr' => 'Maldivi','name_en' => 'Maldives','name_ru' => 'Мальдивские о-ва','local_name' => 'Maldives','global_name' => 'Maldives','code' => 'MV','dial_code' => '960'),
            array('name_hr' => 'Malezija','name_en' => 'Malaysia','name_ru' => 'Малайзия','local_name' => 'Malaysia','global_name' => 'Malaysia','code' => 'MY','dial_code' => '60'),
            array('name_hr' => 'Mali','name_en' => 'Mali','name_ru' => 'Мали','local_name' => 'Mali','global_name' => 'Mali','code' => 'ML','dial_code' => '223'),
            array('name_hr' => 'Malta','name_en' => 'Malta','name_ru' => 'Мальта','local_name' => 'Malta','global_name' => 'Malta','code' => 'MT','dial_code' => '356'),
            array('name_hr' => 'Maroko','name_en' => 'Morocco','name_ru' => 'Марокко','local_name' => '‫المغرب‬‎','global_name' => 'Morocco','code' => 'MA','dial_code' => '212'),
            array('name_hr' => 'Maršalovi Otoci','name_en' => 'Marshall Islands','name_ru' => 'Маршалловы о-ва','local_name' => 'Marshall Islands','global_name' => 'Marshall Islands','code' => 'MH','dial_code' => '692'),
            array('name_hr' => 'Martinik','name_en' => 'Martinique','name_ru' => 'Мартиника','local_name' => 'Martinique','global_name' => 'Martinique','code' => 'MQ','dial_code' => '596'),
            array('name_hr' => 'Mauricijus','name_en' => 'Mauritius','name_ru' => 'Маврикий','local_name' => 'Moris','global_name' => 'Mauritius','code' => 'MU','dial_code' => '230'),
            array('name_hr' => 'Mauritanija','name_en' => 'Mauritania','name_ru' => 'Мавритания','local_name' => '‫موريتانيا‬‎','global_name' => 'Mauritania','code' => 'MR','dial_code' => '222'),
            array('name_hr' => 'Meksiko','name_en' => 'Mexico','name_ru' => 'Мексика','local_name' => 'México','global_name' => 'Mexico','code' => 'MX','dial_code' => '52'),
            array('name_hr' => 'Mijanmar (Burma)','name_en' => 'Myanmar','name_ru' => 'Мьянма (Бирма)','local_name' => 'မြန်မာ','global_name' => 'Myanmar','code' => 'MM','dial_code' => '95'),
            array('name_hr' => 'Mikronezija','name_en' => 'Micronesia','name_ru' => 'Федеративные Штаты Микронезии','local_name' => 'Micronesia','global_name' => 'Micronesia','code' => 'FM','dial_code' => '691'),
            array('name_hr' => 'Moldavija','name_en' => 'Moldova','name_ru' => 'Молдова','local_name' => 'Republica Moldova','global_name' => 'Moldova','code' => 'MD','dial_code' => '373'),
            array('name_hr' => 'Monako','name_en' => 'Monaco','name_ru' => 'Монако','local_name' => 'Monaco','global_name' => 'Monaco','code' => 'MC','dial_code' => '377'),
            array('name_hr' => 'Mongolija','name_en' => 'Mongolia','name_ru' => 'Монголия','local_name' => 'Монгол','global_name' => 'Mongolia','code' => 'MN','dial_code' => '976'),
            array('name_hr' => 'Montserat','name_en' => 'Montserrat','name_ru' => 'Монтсеррат','local_name' => 'Montserrat','global_name' => 'Montserrat','code' => 'MS','dial_code' => '1664'),
            array('name_hr' => 'Mozambik','name_en' => 'Mozambique','name_ru' => 'Мозамбик','local_name' => 'Moçambique','global_name' => 'Mozambique','code' => 'MZ','dial_code' => '258'),
            array('name_hr' => 'Namibija','name_en' => 'Namibia','name_ru' => 'Намибия','local_name' => 'Namibia','global_name' => 'Namibia','code' => 'NA','dial_code' => '264'),
            array('name_hr' => 'Nauru','name_en' => 'Nauru','name_ru' => 'Науру','local_name' => 'Nauru','global_name' => 'Nauru','code' => 'NR','dial_code' => '674'),
            array('name_hr' => 'Nepal','name_en' => 'Nepal','name_ru' => 'Непал','local_name' => 'नेपाल','global_name' => 'Nepal','code' => 'NP','dial_code' => '977'),
            array('name_hr' => 'Niger','name_en' => 'Niger','name_ru' => 'Нигер','local_name' => 'Nijar','global_name' => 'Niger','code' => 'NE','dial_code' => '227'),
            array('name_hr' => 'Nigerija','name_en' => 'Nigeria','name_ru' => 'Нигерия','local_name' => 'Nigeria','global_name' => 'Nigeria','code' => 'NG','dial_code' => '234'),
            array('name_hr' => 'Nikaragva','name_en' => 'Nicaragua','name_ru' => 'Никарагуа','local_name' => 'Nicaragua','global_name' => 'Nicaragua','code' => 'NI','dial_code' => '505'),
            array('name_hr' => 'Niue','name_en' => 'Niue','name_ru' => 'Ниуе','local_name' => 'Niue','global_name' => 'Niue','code' => 'NU','dial_code' => '683'),
            array('name_hr' => 'Nizozemska','name_en' => 'Netherlands','name_ru' => 'Нидерланды','local_name' => 'Nederland','global_name' => 'Netherlands','code' => 'NL','dial_code' => '31'),
            array('name_hr' => 'Norveška','name_en' => 'Norway','name_ru' => 'Норвегия','local_name' => 'Norge','global_name' => 'Norway','code' => 'NO','dial_code' => '47'),
            array('name_hr' => 'Nova Kaledonija','name_en' => 'New Caledonia','name_ru' => 'Новая Каледония','local_name' => 'Nouvelle-Calédonie','global_name' => 'New Caledonia','code' => 'NC','dial_code' => '687'),
            array('name_hr' => 'Novi Zeland','name_en' => 'New Zealand','name_ru' => 'Новая Зеландия','local_name' => 'New Zealand','global_name' => 'New Zealand','code' => 'NZ','dial_code' => '64'),
            array('name_hr' => 'Njemačka','name_en' => 'Germany','name_ru' => 'Германия','local_name' => 'Deutschland','global_name' => 'Germany','code' => 'DE','dial_code' => '49'),
            array('name_hr' => 'Oman','name_en' => 'Oman','name_ru' => 'Оман','local_name' => 'عُمان‬‎','global_name' => 'Oman','code' => 'OM','dial_code' => '968'),
            array('name_hr' => 'Alandski otoci','name_en' => 'Åland Islands','name_ru' => 'Аландские о-ва','local_name' => 'Åland','global_name' => 'Åland Islands','code' => 'AX','dial_code' => ''),
            array('name_hr' => 'Otoci Pitcairn','name_en' => 'Pitcairn Islands','name_ru' => 'Питкэрн','local_name' => 'Pitcairn Islands','global_name' => 'Pitcairn Islands','code' => 'PN','dial_code' => ''),
            array('name_hr' => 'Otok Ascension','name_en' => 'Ascension Island','name_ru' => 'О-в Вознесения','local_name' => 'Ascension Island','global_name' => 'Ascension Island','code' => 'AC','dial_code' => '247'),
            array('name_hr' => 'Otok Bouvet','name_en' => 'Bouvet Island','name_ru' => 'О-в Буве','local_name' => 'Bouvet Island','global_name' => 'Bouvet Island','code' => 'BV','dial_code' => ''),
            array('name_hr' => 'Otok Clipperton','name_en' => 'Clipperton Island','name_ru' => 'О-в Клиппертон','local_name' => 'Île Clipperton','global_name' => 'Clipperton Island','code' => 'CP','dial_code' => ''),
            array('name_hr' => 'Otok Heard i Otoci McDonald','name_en' => 'Heard Island and McDonald Islands','name_ru' => 'О-ва Херд и Макдональд','local_name' => 'Heard Island and McDonald Islands','global_name' => 'Heard Island and McDonald Islands','code' => 'HM','dial_code' => ''),
            array('name_hr' => 'Otok Man','name_en' => 'Isle of Man','name_ru' => 'О-в Мэн','local_name' => 'Isle of Man','global_name' => 'Isle of Man','code' => 'IM','dial_code' => ''),
            array('name_hr' => 'Otok Norfolk','name_en' => 'Norfolk Island','name_ru' => 'О-в Норфолк','local_name' => 'Norfolk Island','global_name' => 'Norfolk Island','code' => 'NF','dial_code' => '6723'),
            array('name_hr' => 'Pakistan','name_en' => 'Pakistan','name_ru' => 'Пакистан','local_name' => 'پاکستان','global_name' => 'Pakistan','code' => 'PK','dial_code' => '92'),
            array('name_hr' => 'Palau','name_en' => 'Palau','name_ru' => 'Палау','local_name' => 'Palau','global_name' => 'Palau','code' => 'PW','dial_code' => '680'),
            array('name_hr' => 'Palestina','name_en' => 'Palestine','name_ru' => 'Палестина','local_name' => 'فلسطين‬‎','global_name' => 'Palestine','code' => 'PS','dial_code' => '970'),
            array('name_hr' => 'Panama','name_en' => 'Panama','name_ru' => 'Панама','local_name' => 'Panamá','global_name' => 'Panama','code' => 'PA','dial_code' => '507'),
            array('name_hr' => 'Papua Nova Gvineja','name_en' => 'Papua New Guinea','name_ru' => 'Папуа – Новая Гвинея','local_name' => 'Papua New Guinea','global_name' => 'Papua New Guinea','code' => 'PG','dial_code' => '675'),
            array('name_hr' => 'Paragvaj','name_en' => 'Paraguay','name_ru' => 'Парагвай','local_name' => 'Paraguay','global_name' => 'Paraguay','code' => 'PY','dial_code' => '595'),
            array('name_hr' => 'Peru','name_en' => 'Peru','name_ru' => 'Перу','local_name' => 'Perú','global_name' => 'Peru','code' => 'PE','dial_code' => '51'),
            array('name_hr' => 'Poljska','name_en' => 'Poland','name_ru' => 'Польша','local_name' => 'Polska','global_name' => 'Poland','code' => 'PL','dial_code' => '48'),
            array('name_hr' => 'Portoriko','name_en' => 'Puerto Rico','name_ru' => 'Пуэрто-Рико','local_name' => 'Puerto Rico','global_name' => 'Puerto Rico','code' => 'PR','dial_code' => '1787'),
            array('name_hr' => 'Portugal','name_en' => 'Portugal','name_ru' => 'Португалия','local_name' => 'Portugal','global_name' => 'Portugal','code' => 'PT','dial_code' => '351'),
            array('name_hr' => 'Reunion','name_en' => 'Reunion','name_ru' => 'Реюньон','local_name' => 'Réunion','global_name' => 'Reunion','code' => 'RE','dial_code' => '262'),
            array('name_hr' => 'Ruanda','name_en' => 'Rwanda','name_ru' => 'Руанда','local_name' => 'Rwanda','global_name' => 'Rwanda','code' => 'RW','dial_code' => '250'),
            array('name_hr' => 'Rumunjska','name_en' => 'Romania','name_ru' => 'Румыния','local_name' => 'România','global_name' => 'Romania','code' => 'RO','dial_code' => '40'),
            array('name_hr' => 'Rusija','name_en' => 'Russia','name_ru' => 'Россия','local_name' => 'Россия','global_name' => 'Russia','code' => 'RU','dial_code' => '7'),
            array('name_hr' => 'Samoa','name_en' => 'Samoa','name_ru' => 'Самоа','local_name' => 'Samoa','global_name' => 'Samoa','code' => 'WS','dial_code' => '685'),
            array('name_hr' => 'San Marino','name_en' => 'San Marino','name_ru' => 'Сан-Марино','local_name' => 'San Marino','global_name' => 'San Marino','code' => 'SM','dial_code' => '378'),
            array('name_hr' => 'Saudijska Arabija','name_en' => 'Saudi Arabia','name_ru' => 'Саудовская Аравия','local_name' => '‫المملكة العربية السعودية','global_name' => 'Saudi Arabia','code' => 'SA','dial_code' => '966'),
            array('name_hr' => 'Sejšeli','name_en' => 'Seychelles','name_ru' => 'Сейшельские о-ва','local_name' => 'Seychelles','global_name' => 'Seychelles','code' => 'SC','dial_code' => '248'),
            array('name_hr' => 'Senegal','name_en' => 'Senegal','name_ru' => 'Сенегал','local_name' => 'Sénégal','global_name' => 'Senegal','code' => 'SN','dial_code' => '221'),
            array('name_hr' => 'Sijera Leone','name_en' => 'Sierra Leone','name_ru' => 'Сьерра-Леоне','local_name' => 'Sierra Leone','global_name' => 'Sierra Leone','code' => 'SL','dial_code' => '232'),
            array('name_hr' => 'Singapur','name_en' => 'Singapore','name_ru' => 'Сингапур','local_name' => 'Singapore','global_name' => 'Singapore','code' => 'SG','dial_code' => '65'),
            array('name_hr' => 'Sint Maarten','name_en' => 'Sint Maarten','name_ru' => 'Синт-Мартен','local_name' => 'Sint Maarten','global_name' => 'Sint Maarten','code' => 'SX','dial_code' => '1721'),
            array('name_hr' => 'Sirija','name_en' => 'Syria','name_ru' => 'Сирия','local_name' => 'سوريا‬‎','global_name' => 'Syria','code' => 'SY','dial_code' => '963'),
            array('name_hr' => 'Sjedinjene Američke Države','name_en' => 'United States','name_ru' => 'США','local_name' => 'United States','global_name' => 'United States','code' => 'US','dial_code' => '1'),
            array('name_hr' => 'Sjeverna Koreja','name_en' => 'North Korea','name_ru' => 'Северная Корея','local_name' => '조선 민주주의 인민 공화국','global_name' => 'North Korea','code' => 'KP','dial_code' => '850'),
            array('name_hr' => 'Sjeverni Marijanski Otoci','name_en' => 'Northern Mariana Islands','name_ru' => 'Северные Марианские о-ва','local_name' => 'Northern Mariana Islands','global_name' => 'Northern Mariana Islands','code' => 'MP','dial_code' => '1'),
            array('name_hr' => 'Slovačka','name_en' => 'Slovakia','name_ru' => 'Словакия','local_name' => 'Slovensko','global_name' => 'Slovakia','code' => 'SK','dial_code' => '421'),
            array('name_hr' => 'Slovenija','name_en' => 'Slovenia','name_ru' => 'Словения','local_name' => 'Slovenija','global_name' => 'Slovenia','code' => 'SI','dial_code' => '386'),
            array('name_hr' => 'Solomonski Otoci','name_en' => 'Solomon Islands','name_ru' => 'Соломоновы о-ва','local_name' => 'Solomon Islands','global_name' => 'Solomon Islands','code' => 'SB','dial_code' => '677'),
            array('name_hr' => 'Somalija','name_en' => 'Somalia','name_ru' => 'Сомали','local_name' => 'Soomaaliya','global_name' => 'Somalia','code' => 'SO','dial_code' => '252'),
            array('name_hr' => 'Srbija','name_en' => 'Serbia','name_ru' => 'Сербия','local_name' => 'Србија','global_name' => 'Serbia','code' => 'RS','dial_code' => '381'),
            array('name_hr' => 'Srednjoafrička Republika','name_en' => 'Central African Republic','name_ru' => 'ЦАР','local_name' => 'République centrafricaine','global_name' => 'Central African Republic','code' => 'CF','dial_code' => '236'),
            array('name_hr' => 'Sudan','name_en' => 'Sudan','name_ru' => 'Судан','local_name' => 'السودان','global_name' => 'Sudan','code' => 'SD','dial_code' => '249'),
            array('name_hr' => 'Surinam','name_en' => 'Suriname','name_ru' => 'Суринам','local_name' => 'Suriname','global_name' => 'Suriname','code' => 'SR','dial_code' => '597'),
            array('name_hr' => 'Svalbard i Jan Mayen','name_en' => 'Svalbard and Jan Mayen','name_ru' => 'Свальбард и Ян-Майен','local_name' => 'Svalbard og Jan Mayen','global_name' => 'Svalbard and Jan Mayen','code' => 'SJ','dial_code' => ''),
            array('name_hr' => 'Svazi','name_en' => 'Swaziland','name_ru' => 'Свазиленд','local_name' => 'Swaziland','global_name' => 'Swaziland','code' => 'SZ','dial_code' => '268'),
            array('name_hr' => 'Sveta Helena','name_en' => 'Saint Helena','name_ru' => 'О-в Св. Елены','local_name' => 'Saint Helena','global_name' => 'Saint Helena','code' => 'SH','dial_code' => '290'),
            array('name_hr' => 'Sveta Lucija','name_en' => 'Saint Lucia','name_ru' => 'Сент-Люсия','local_name' => 'Saint Lucia','global_name' => 'Saint Lucia','code' => 'LC','dial_code' => '1758'),
            array('name_hr' => 'Sveti Bartolomej','name_en' => 'Saint Barthélemy','name_ru' => 'О-в Св. Бартоломея','local_name' => 'Saint-Barthélémy','global_name' => 'Saint Barthélemy','code' => 'BL','dial_code' => '590'),
            array('name_hr' => 'Sveti Kristofor i Nevis','name_en' => 'Saint Kitts and Nevis','name_ru' => 'Сент-Китс и Невис','local_name' => 'Saint Kitts and Nevis','global_name' => 'Saint Kitts and Nevis','code' => 'KN','dial_code' => '1869'),
            array('name_hr' => 'Sveti Martin','name_en' => 'Saint Martin','name_ru' => 'О-в Святого Мартина','local_name' => 'Saint-Martin (partie française)','global_name' => 'Saint Martin','code' => 'MF','dial_code' => '590'),
            array('name_hr' => 'Sveti Petar i Mikelon','name_en' => 'Saint Pierre and Miquelon','name_ru' => 'Сен-Пьер и Микелон','local_name' => 'Saint-Pierre-et-Miquelon','global_name' => 'Saint Pierre and Miquelon','code' => 'PM','dial_code' => '508'),
            array('name_hr' => 'Sveti Toma i Prinsipe','name_en' => 'Sao Tome and Principe','name_ru' => 'Сан-Томе и Принсипи','local_name' => 'São Tomé e Príncipe','global_name' => 'Sao Tome and Principe','code' => 'ST','dial_code' => '239'),
            array('name_hr' => 'Sveti Vincent i Grenadini','name_en' => 'Saint Vincent Grenadines','name_ru' => 'Сент-Винсент и Гренадины','local_name' => 'Saint Vincent and the Grenadines','global_name' => 'Saint Vincent Grenadines','code' => 'VC','dial_code' => '1784'),
            array('name_hr' => 'Španjolska','name_en' => 'Spain','name_ru' => 'Испания','local_name' => 'España','global_name' => 'Spain','code' => 'ES','dial_code' => '34'),
            array('name_hr' => 'Šri Lanka','name_en' => 'Sri Lanka','name_ru' => 'Шри-Ланка','local_name' => 'ශ්‍රී ලංකාව','global_name' => 'Sri Lanka','code' => 'LK','dial_code' => '94'),
            array('name_hr' => 'Švedska','name_en' => 'Sweden','name_ru' => 'Швеция','local_name' => 'Sverige','global_name' => 'Sweden','code' => 'SE','dial_code' => '46'),
            array('name_hr' => 'Švicarska','name_en' => 'Switzerland','name_ru' => 'Швейцария','local_name' => 'Schweiz','global_name' => 'Switzerland','code' => 'CH','dial_code' => '41'),
            array('name_hr' => 'Tadžikistan','name_en' => 'Tajikistan','name_ru' => 'Таджикистан','local_name' => 'Tajikistan','global_name' => 'Tajikistan','code' => 'TJ','dial_code' => '992'),
            array('name_hr' => 'Tajland','name_en' => 'Thailand','name_ru' => 'Таиланд','local_name' => 'ไทย','global_name' => 'Thailand','code' => 'TH','dial_code' => '66'),
            array('name_hr' => 'Tajvan','name_en' => 'Taiwan','name_ru' => 'Тайвань','local_name' => '台灣','global_name' => 'Taiwan','code' => 'TW','dial_code' => '886'),
            array('name_hr' => 'Tanzanija','name_en' => 'Tanzania','name_ru' => 'Танзания','local_name' => 'Tanzania','global_name' => 'Tanzania','code' => 'TZ','dial_code' => '255'),
            array('name_hr' => 'Togo','name_en' => 'Togo','name_ru' => 'Того','local_name' => 'Togo','global_name' => 'Togo','code' => 'TG','dial_code' => '228'),
            array('name_hr' => 'Tokelau','name_en' => 'Tokelau','name_ru' => 'Токелау','local_name' => 'Tokelau','global_name' => 'Tokelau','code' => 'TK','dial_code' => '690'),
            array('name_hr' => 'Tonga','name_en' => 'Tonga','name_ru' => 'Тонга','local_name' => 'Tonga','global_name' => 'Tonga','code' => 'TO','dial_code' => '676'),
            array('name_hr' => 'Trinidad i Tobago','name_en' => 'Trinidad and Tobago','name_ru' => 'Тринидад и Тобаго','local_name' => 'Trinidad and Tobago','global_name' => 'Trinidad and Tobago','code' => 'TT','dial_code' => '1868'),
            array('name_hr' => 'Tristan da Cunha','name_en' => 'Tristan da Cunha','name_ru' => 'Тристан-да-Кунья','local_name' => 'Tristan da Cunha','global_name' => 'Tristan da Cunha','code' => 'TA','dial_code' => ''),
            array('name_hr' => 'Tunis','name_en' => 'Tunisia','name_ru' => 'Тунис','local_name' => '‫تونس‬‎','global_name' => 'Tunisia','code' => 'TN','dial_code' => '216'),
            array('name_hr' => 'Turkmenistan','name_en' => 'Turkmenistan','name_ru' => 'Туркменистан','local_name' => 'Turkmenistan','global_name' => 'Turkmenistan','code' => 'TM','dial_code' => '993'),
            array('name_hr' => 'Turkski i Kaikos Otoci','name_en' => 'Turks and Caicos','name_ru' => 'О-ва Тёркс и Кайкос','local_name' => 'Turks and Caicos Islands','global_name' => 'Turks and Caicos','code' => 'TC','dial_code' => '1649'),
            array('name_hr' => 'Turska','name_en' => 'Turkey','name_ru' => 'Турция','local_name' => 'Türkiye','global_name' => 'Turkey','code' => 'TR','dial_code' => '90'),
            array('name_hr' => 'Tuvalu','name_en' => 'Tuvalu','name_ru' => 'Тувалу','local_name' => 'Tuvalu','global_name' => 'Tuvalu','code' => 'TV','dial_code' => '688'),
            array('name_hr' => 'Uganda','name_en' => 'Uganda','name_ru' => 'Уганда','local_name' => 'Uganda','global_name' => 'Uganda','code' => 'UG','dial_code' => '256'),
            array('name_hr' => 'Ujedinjene Države Manjih Pacifičkih Otoka','name_en' => 'US Minor Outlying Islands','name_ru' => 'Внешние малые о-ва (США)','local_name' => 'US Outlying Islands','global_name' => 'US Minor Outlying Islands','code' => 'UM','dial_code' => ''),
            array('name_hr' => 'Ujedinjeni Arapski Emirati','name_en' => 'United Arab Emirates','name_ru' => 'ОАЭ','local_name' => '‫الإمارات العربية المتحدة‬‎','global_name' => 'United Arab Emirates','code' => 'AE','dial_code' => '971'),
            array('name_hr' => 'Ukrajina','name_en' => 'Ukraine','name_ru' => 'Украина','local_name' => 'Україна','global_name' => 'Ukraine','code' => 'UA','dial_code' => '380'),
            array('name_hr' => 'Urugvaj','name_en' => 'Uruguay','name_ru' => 'Уругвай','local_name' => 'Uruguay','global_name' => 'Uruguay','code' => 'UY','dial_code' => '598'),
            array('name_hr' => 'Uzbekistan','name_en' => 'Uzbekistan','name_ru' => 'Узбекистан','local_name' => 'Ўзбекистон','global_name' => 'Uzbekistan','code' => 'UZ','dial_code' => '998'),
            array('name_hr' => 'Vanuatu','name_en' => 'Vanuatu','name_ru' => 'Вануату','local_name' => 'Vanuatu','global_name' => 'Vanuatu','code' => 'VU','dial_code' => '678'),
            array('name_hr' => 'Velika Britanija','name_en' => 'United Kingdom','name_ru' => 'Великобритания','local_name' => 'United Kingdom','global_name' => 'United Kingdom','code' => 'GB','dial_code' => '44'),
            array('name_hr' => 'Venezuela','name_en' => 'Venezuela','name_ru' => 'Венесуэла','local_name' => 'Venezuela','global_name' => 'Venezuela','code' => 'VE','dial_code' => '58'),
            array('name_hr' => 'Vijetnam','name_en' => 'Vietnam','name_ru' => 'Вьетнам','local_name' => 'Việt Nam','global_name' => 'Vietnam','code' => 'VN','dial_code' => '84'),
            array('name_hr' => 'Wallis i Futuna','name_en' => 'Wallis and Futuna','name_ru' => 'Уоллис и Футуна','local_name' => 'Wallis and Futuna','global_name' => 'Wallis and Futuna','code' => 'WF','dial_code' => '681'),
            array('name_hr' => 'Zambija','name_en' => 'Zambia','name_ru' => 'Замбия','local_name' => 'Zambia','global_name' => 'Zambia','code' => 'ZM','dial_code' => '260'),
            array('name_hr' => 'Zapadna Sahara','name_en' => 'Western Sahara','name_ru' => 'Западная Сахара','local_name' => '‫الصحراء الغربية','global_name' => 'Western Sahara','code' => 'EH','dial_code' => ''),
            array('name_hr' => 'Zeleni Rt','name_en' => 'Cape Verde','name_ru' => 'Кабо-Верде','local_name' => 'Kabu Verdi','global_name' => 'Cape Verde','code' => 'CV','dial_code' => '238'),
            array('name_hr' => 'Zimbabve','name_en' => 'Zimbabwe','name_ru' => 'Зимбабве','local_name' => 'Zimbabwe','global_name' => 'Zimbabwe','code' => 'ZW','dial_code' => '263'),
            array('name_hr' => 'Bolivija','name_en' => 'Bolivia','name_ru' => 'Боливия','local_name' => 'Bolivia','global_name' => 'Bolivia','code' => 'BO','dial_code' => '591'),
            array('name_hr' => 'Vatikan','name_en' => 'Vatican City','name_ru' => 'Ватикан','local_name' => 'Status Civitatis Vaticanae','global_name' => 'Vatican City','code' => 'VA','dial_code' => '379'),
            array('name_hr' => 'Nizozemski Antili','name_en' => 'Netherlands Antilles','name_ru' => 'Нидерландские Антильские острова','local_name' => 'Nederlandse Antillen','global_name' => 'Netherlands Antilles','code' => 'AN','dial_code' => '599')
        );

        return $countries;
    }
}
